version: '3.8'

volumes:
  orchestrator_data:
  portainer_data:

services:
  # MCP Orchestrator Proxy - Manages all MCPs as subprocesses
  mcp-orchestrator-proxy:
    build: .
    container_name: mcp-orchestrator-proxy
    restart: unless-stopped
    network_mode: "host"  # Use host network for simplicity
    volumes:
      - ./config:/app/config
      - orchestrator_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker MCP if needed
    environment:
      - NODE_ENV=production
      - PYTHONPATH=/app
      # GitHub token for GitHub MCP
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      # ComfyUI URL if needed
      - COMFYUI_URL=${COMFYUI_URL:-http://localhost:8188}
    ports:
      - "8080:8080"  # Orchestrator API port

  # Portainer for Container Management (optional)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
