version: '3.8'

# No network definition needed for host mode

volumes:
  neo4j_data:
  neo4j_logs:
  mongodb_data:
  redis_data:
  portainer_data:
  comfyui_data:
  minio_data:

services:
  # Traefik - Using host network
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    network_mode: "host"  # Use host network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

  # Neo4j Memory System - Using host network
  neo4j:
    image: neo4j:2025.05.0
    container_name: neo4j
    restart: unless-stopped
    network_mode: "host"  # Use host network
    environment:
      - NEO4J_AUTH=neo4j/secure_password_here
      - NEO4J_server_memory_pagecache_size=2G
      - NEO4J_server_memory_heap_max__size=2G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "secure_password_here", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MongoDB Document Store - Using host network
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    network_mode: "host"  # Use host network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secure_password
      - MONGO_INITDB_DATABASE=mcp
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache - Using host network
  redis:
    image: redis:7.2.3-alpine
    container_name: redis
    restart: unless-stopped
    network_mode: "host"  # Use host network
    command: redis-server --appendonly yes --maxmemory 2gb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Portainer Management - Using host network
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    network_mode: "host"  # Use host network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  # ComfyUI - Using host network
  comfyui:
    image: yawnk/comfyui-boot:cu124-slim
    container_name: comfyui
    restart: unless-stopped
    network_mode: "host"  # Use host network
    volumes:
      - comfyui_data:/root
      - ./models:/root/ComfyUI/models
      - ./output:/root/ComfyUI/output
    environment:
      - CLI_ARGS=""
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # MCP Orchestrator - Using host network
  mcp-orchestrator:
    image: node:20-slim
    container_name: mcp-orchestrator
    restart: unless-stopped
    network_mode: "host"  # Use host network
    working_dir: /app
    volumes:
      - ./mcp-orchestrator:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: npm start
    depends_on:
      - mongodb
      - redis

  # MCP Memory Service - Using host network
  mcp-memory:
    image: node:20-slim
    container_name: mcp-memory
    restart: unless-stopped
    network_mode: "host"  # Use host network
    working_dir: /app
    volumes:
      - ./mcp-memory-blockchain:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3001
      - NEO4J_URI=bolt://localhost:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=secure_password_here
    command: npm start
    depends_on:
      neo4j:
        condition: service_healthy

  # MCP Time Precision - Using host network
  mcp-time-precision:
    image: node:20-slim
    container_name: mcp-time-precision
    restart: unless-stopped
    network_mode: "host"  # Use host network
    working_dir: /app
    volumes:
      - ./mcp-time-precision:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3002
    command: npm start

  # MinIO Object Storage - Using host network
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    network_mode: "host"  # Use host network
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"